name: Bash Loop Example

on: [push]

jobs:
  run-bash-loop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Bash loop
        run: from_start/git-for-dev/whilewhileloop.sh
